version: "3.8"

services:
  passmanagerdb:
    container_name: passmanagerdb
    image: mongo:4.4.2
    restart: always
    volumes:
      - ./init-db/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_ROOT_USER:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_ROOT_PASS:-changeme}
      DB_USER: ${DB_USER:-adminpassmanager}
      DB_PASS: ${DB_PASS:-changeme76}
      DB_NAME: ${DB_NAME:-passmanager}

  mongo-express-passmanagerdb:
    container_name: mongo-express-passmanager
    image: mongo-express
    restart: always
    ports:
      - 8888:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_ROOT_USER:-admin}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_ROOT_PASS:-changeme}
      ME_CONFIG_MONGODB_SERVER: passmanagerdb
